services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT-8080}:${APP_PORT-8080}"
    restart: always
    environment:
      - APP_HOST=${APP_HOST-localhost}
      - APP_PORT=${APP_PORT-8080}
      - DB_CONNECTION=${DB_CONNECTION}
      - SERVICE_NAME=${SERVICE_NAME}
    # networks:
    #   - mynetwork

# networks:
#   mynetwork:
#     external: true